config/routes.rb
Rails.application.routes.draw do

  resources :representatives
  resources :signatures
  resources :representatives
  resources :contractors
  devise_for :users
  scope "/Admin" do
    resources :users, :enquiries, :roles, :contractors, :representatives
    get '/enquiries/:id/print', to: 'enquiries#print'
  end

  scope "/Aanvrager" do
    resources :users, :enquiries
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get "search/index"

root 'enquiries#index'
  get 'welcome/Index'

end

app/models/representative.rb
class Representative < ActiveRecord::Base
  belongs_to :signature
end

app/controllers/representatives_controller.rb
class RepresentativesController < ApplicationController
  before_action :set_representative, only: [:show, :edit, :update, :destroy]

  # GET /representatives
  # GET /representatives.json
  def index
    @representatives = Representative.all
  end

  # GET /representatives/1
  # GET /representatives/1.json
  def show
  end

  # GET /representatives/new
  def new
    @representative = Representative.new
  end

  # GET /representatives/1/edit
  def edit
  end

  # POST /representatives
  # POST /representatives.json
  def create
    @representative = Representative.new(representative_params)

    respond_to do |format|
      if @representative.save
        format.html { redirect_to @representative, notice: 'Representative was successfully created.' }
        format.json { render :show, status: :created, location: @representative }
      else
        format.html { render :new }
        format.json { render json: @representative.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /representatives/1
  # PATCH/PUT /representatives/1.json
  def update
    respond_to do |format|
      if @representative.update(representative_params)
        format.html { redirect_to @representative, notice: 'Representative was successfully updated.' }
        format.json { render :show, status: :ok, location: @representative }
      else
        format.html { render :edit }
        format.json { render json: @representative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /representatives/1
  # DELETE /representatives/1.json
  def destroy
    @representative.destroy
    respond_to do |format|
      format.html { redirect_to representatives_url, notice: 'Representative was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_representative
      @representative = Representative.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def representative_params
      params.require(:representative).permit(:name, :email, :telephone)
    end
end

app/helpers/representatives_helper.rb
module RepresentativesHelper
end

app/views/representatives/_form.html.erb
<%= form_for(@representative) do |f| %>
    <% if @representative.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@representative.errors.count, "error") %> prohibited this representative from being
            saved:</h2>

          <ul>
            <% @representative.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    </div>

    <div class="field">
      <%= f.label :Naam %><br>
      <%= f.text_field :name %>
    </div>


    <div class="field">
      <%= f.label :Telefoon %><br>
      <%= f.number_field :telephone %>
    </div>


    <div class="field">
      <%= f.label :email %><br>
      <%= f.email_field :email %>
    </div>

    <div class="field">
      <%= f.label :handtekening %><br>
      <%= f.email_field :signature %>
    </div>


    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/representatives/edit.html.erb
<h1>Editing Representative</h1>

<%= render 'form' %>

<%= link_to 'Show', @representative %> |
<%= link_to 'Back', representatives_path %>

app/views/representatives/index.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Werkvergunningssysteem", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>

        <li>
          <% if can? :update, @enquiry %>
              <%= link_to 'Gebruikers', users_path %></li>
          <% end %>

        <li>
          <% if can? :update, @enquiry %>
           <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Beheer <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Aannemers", contractors_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
                </li>
              </ul>
        <% end %>


          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
              </li>
            </ul>
          </li>

          </ul>
    </nav>
  </div>
</header>
<br><br><br><br>

<p id="notice"><%= notice %></p>

<div id="main-container" class="container-fluid">
  <div class="row">
    <div id="sidebar" class="col-xs-2">
      <!-- sidebar content -->
      <% if can? :manage, @enquiry %>
          <%= link_to 'Nieuwe gemachtigde', new_representative_path, class: 'btn btn-success' %>
      <% end %>
    </div>

    <div id="content" class="col-xs-10">
      <p> boodschap</p>

      <h1>Goedgekeurde gemachtigden</h1>

      <table class="table table-striped">
        <thead>
        <tr>
          <th>Naam</th>
          <th>Telefoon</th>
          <th>Email</th>
          <th>Handtekening</th>

        </tr>
        </thead>

        <tbody>
        <% @representatives.each do |r| %>
            <tr>
              <td><%= r.name %></td>
              <td><%=r.telephone %></td>
              <td><%= r.email %></td>
              <td><%= r.signature %></td>

              <td><%= link_to 'Show', r, class: 'btn btn-primary btn-xs' %></td>
              <td><%= link_to 'Edit', edit_representative_path(r), class: 'btn btn-info btn-xs'  %></td>
              <td><%= link_to 'Destroy', r, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<br>


<%= link_to 'New Contractor', new_contractor_path %>

app/views/representatives/new.html.erb
<h1>New Representative</h1>

<%= render 'form' %>

<%= link_to 'Back', representatives_path %>

app/views/representatives/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>ID:</strong>
  <%= @representative.id %>
</p>

<p>
  <strong>naam:</strong>
  <%= @representative.name %>
</p>

<p>
  <strong>email:</strong>
  <%= @representative.email %>
</p>

<p>
  <strong>telefoon:</strong>
  <%= @representative.telephone %>
</p>

<p>
  <strong>Handtekening:</strong>
  <%= @representative.signature %>
</p>

<%= link_to 'Edit', edit_representative_path(@representative) %> |
<%= link_to 'Back', representatives_path %>