config/routes.rb
Rails.application.routes.draw do

  resources :representatives
  resources :signatures
  resources :representatives
  resources :contractors
  devise_for :users
  scope "/Admin" do
    resources :users, :enquiries, :roles, :contractors, :representatives
    get '/enquiries/:id/print', to: 'enquiries#print'
  end

  scope "/Aanvrager" do
    resources :users, :enquiries
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get "search/index"

root 'enquiries#index'
  get 'welcome/Index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 belongs_to :role
  has_many :enquiries

  validates_presence_of :name
  before_save :assign_role

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'


  def assign_role
    self.role = Role.find_by name: "Aanvrager" if self.role.nil?
  end

  def admin?
    self.role.name == "Admin"
  end

  def aanvrager?
    self.role.name == "Aanvrager"
  end


  #after_create :send_welcome_mail
  #def send_welcome_mail
  #  ModelMailer.welcome_email(self).deliver
  #end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
   # GET /users
  # GET /users.json
  def index
    @users = User.all

      #@enquiry  = Enquiry.all
      #@enquirie= Enquiry.all
      @users_grid = initialize_grid(User, order: 'id', per_page: 15, include: :role)

  end

  # GET /users/1
  # GET /users/1.json

    def show
      @joined_on = @user.created_at.to_formatted_s(:short)
      if @user.current_sign_in_at
        @last_login = @user.current_sign_in_at.to_formatted_s(:short)
      else
        @last_login = "never"
      end

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome email after save
        ModelMailer.welcome_email(@user).deliver
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }

      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end

    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
    def update
      if user_params[:password].blank?
        user_params.delete(:password)
        user_params.delete(:password_confirmation)
      end

      successfully_updated = if needs_password?(@user, user_params)
                               @user.update(user_params)
                             else
                               @user.update_without_password(user_params)
                             end

      respond_to do |format|
        if successfully_updated
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end


    protected
    def needs_password?(user, params)
      params[:password].present?
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :role_id, :pin)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>

    <div class="field">
    <%= f.label :role_id %><br>
    <%= collection_select(:user, :role_id, Role.all, :id, :name, {prompt: true}) %>
  </div>

    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password, placeholder: "Leave blank if unchanged" %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div id='panel-wrapper'>
  <div id='panel-header' class='text-center'>
    <span class='panel-title'>JPB Werkvergunningen</span>
  </div>
  <div id='panel-body'>
    <div class='row'>
      <div class='col-md-12'>


      <%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div id='panel-wrapper'>
  <div id='panel-header' class='text-center'>
    <span class='panel-title'>JPB Werkvergunningen</span>
  </div>
  <div id='panel-body'>
    <div class='row'>
      <div class='col-md-12'>

<p id="notice"><%= notice %></p>

<div id="main-container" class="container-fluid">
  <div class="row">

    <div id="content" class="col-xs-9">

<p>Geregistreerde gebruikers</p>

      <%= grid(@users_grid, show_filters: :always) do |g|

        g.column name: 'ID', attribute: 'id' , auto_reload: true do |user|
          user.id
        end

        g.column name: 'Naam', attribute: 'name', auto_reload: true do |user|
          user.name
        end


        g.column name: 'Email', attribute: 'email', auto_reload: true do |user|
          user.email
        end

        g.column name: 'Rol', attribute: 'name', assoc: :role, auto_reload: true do |user|
          user.role.name
        end


        g.column do |user|

          link_to 'Edit', edit_user_path(user), class: 'btn btn-info btn-xs'
        end
        g.column do |user|
          link_to 'Show', user, class: 'btn btn-primary btn-xs'
        end
        g.column do |user|
          link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs'
        end
      end %>
      <%= link_to 'Rollen', roles_path, class: 'btn btn-success' %><br>
      <%= link_to 'Nieuwe gebruiker', new_user_path, class: 'btn btn-success' %><br>
    </div>
  </div>
</div>
<br>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div id='panel-wrapper'>
  <div id='panel-header' class='text-center'>
    <span class='panel-title'>JPB Werkvergunningen</span>
  </div>
  <div id='panel-body'>
    <div class='row'>
      <div class='col-md-12'>

      <%= render 'form' %>

<%= link_to 'Back', users_path %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role.name %>
</p>

<p>
  <strong>Joined on:</strong>
  <%= @joined_on %>
</p>
<p>
  <strong>Last logged in on:</strong>
  <%= @last_login %>
</p>
<p>
  <strong>No. times logged in:</strong>
  <%= @user.sign_in_count %>
</p>

<p>
  <strong>Pincode</strong>
  <%= @user.pin %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>