config/routes.rb
Rails.application.routes.draw do

  resources :representatives
  resources :signatures
  resources :representatives
  resources :contractors
  devise_for :users
  scope "/Admin" do
    resources :users, :enquiries, :roles, :contractors, :representatives
    get '/enquiries/:id/print', to: 'enquiries#print'
  end

  scope "/Aanvrager" do
    resources :users, :enquiries
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get "search/index"

root 'enquiries#index'
  get 'welcome/Index'

end

app/models/contractor.rb
class Contractor < ActiveRecord::Base
  belongs_to :applicant

end

app/controllers/contractors_controller.rb
class ContractorsController < ApplicationController
  before_action :set_contractor, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /contractors
  # GET /contractors.json
  def index
    @contractors = Contractor.all
  end

  # GET /contractors/1
  # GET /contractors/1.json
  def show
  end

  # GET /contractors/new
  def new
    @contractor = Contractor.new
  end

  # GET /contractors/1/edit
  def edit
  end

  # POST /contractors
  # POST /contractors.json
  def create
    @contractor = Contractor.new(contractor_params)

    respond_to do |format|
      if @contractor.save
        format.html { redirect_to @contractor, notice: 'Contractor was successfully created.' }
        format.json { render :show, status: :created, location: @contractor }
      else
        format.html { render :new }
        format.json { render json: @contractor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contractors/1
  # PATCH/PUT /contractors/1.json
  def update
    respond_to do |format|
      if @contractor.update(contractor_params)
        format.html { redirect_to @contractor, notice: 'Contractor was successfully updated.' }
        format.json { render :show, status: :ok, location: @contractor }
      else
        format.html { render :edit }
        format.json { render json: @contractor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contractors/1
  # DELETE /contractors/1.json
  def destroy
    @contractor.destroy
    respond_to do |format|
      format.html { redirect_to contractors_url, notice: 'Contractor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contractor
      @contractor = Contractor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contractor_params
      params.require(:contractor).permit(:name, :email)
    end
end

app/helpers/contractors_helper.rb
module ContractorsHelper
end

app/views/contractors/_form.html.erb
<%= form_for(@contractor) do |f| %>
  <% if @contractor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contractor.errors.count, "error") %> prohibited this contractor from being saved:</h2>

      <ul>
      <% @contractor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>

        <div class="field">
          <%= f.label :Naam %><br>
          <%= f.text_field :name %>
        </div>


        <div class="field">
          <%= f.label :email %><br>
          <%= f.email_field :email %>
        </div>

  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contractors/edit.html.erb
<h1>Editing Contractor</h1>

<%= render 'form' %>

<%= link_to 'Show', @contractor %> |
<%= link_to 'Back', contractors_path %>

app/views/contractors/index.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Werkvergunningssysteem", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>

        <li>
          <% if can? :update, @enquiry %>
              <%= link_to 'Gebruikers', users_path %></li>
          <% end %>

        <li>
          <% if can? :update, @enquiry %>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Beheer <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Gemachtigden", representatives_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
                </li>
              </ul>
        <% end %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
              </li>
            </ul>
          </li>

          </ul>
    </nav>
  </div>
</header>
<br><br><br><br>

<p id="notice"><%= notice %></p>

<div id="main-container" class="container-fluid">
  <div class="row">
    <div id="sidebar" class="col-xs-2">
      <!-- sidebar content -->
      <% if can? :manage, @enquiry %>
          <%= link_to 'Nieuwe aannemer', new_contractor_path, class: 'btn btn-success' %>
      <% end %>
    </div>

    <div id="content" class="col-xs-10">
      <p> boodschap</p>

<h1>Goedgekeurde aannemers</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Naam</th>
      <th>Email</th>

    </tr>
  </thead>

  <tbody>
    <% @contractors.each do |contractor| %>
      <tr>
        <td><%= contractor.name %></td>
        <td><%= contractor.email %></td>

        <td><%= link_to 'Show', contractor, class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Edit', edit_contractor_path(contractor), class: 'btn btn-info btn-xs'  %></td>
        <td><%= link_to 'Destroy', contractor, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
    </div>
  </div>
</div>
<br>


<%= link_to 'New Contractor', new_contractor_path %>

app/views/contractors/new.html.erb
<h1>Nieuwe aannemer</h1>

<%= render 'form' %>

<%= link_to 'Back', contractors_path %>

app/views/contractors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @contractor.id %>
</p>

<p>
  <strong>naam:</strong>
  <%= @contractor.name %>
</p>

<p>
  <strong>email:</strong>
  <%= @contractor.email %>
</p>

<%= link_to 'Edit', edit_contractor_path(@contractor) %> |
<%= link_to 'Back', contractors_path %>