config/routes.rb
Rails.application.routes.draw do

  resources :representatives
  resources :signatures
  resources :representatives
  resources :contractors
  devise_for :users
  scope "/Admin" do
    resources :users, :enquiries, :roles, :contractors, :representatives
    get '/enquiries/:id/print', to: 'enquiries#print'
  end

  scope "/Aanvrager" do
    resources :users, :enquiries
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get "search/index"

root 'enquiries#index'
  get 'welcome/Index'

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
    @roles_grid = initialize_grid(Role, order: 'id', per_page: 15)
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    if @role.users.length == 0
      @assosciated_users = "None"
    else
      @assosciated_users = @role.users.map(&:name).join(", ")
    end
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :description)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<div id='panel-wrapper'>
  <div id='panel-header' class='text-center'>
    <span class='panel-title'>JPB Werkvergunningen</span>
  </div>
  <div id='panel-body'>
    <div class='row'>
      <div class='col-md-12'>


      <%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

      </div>
    </div>
  </div>
</div>

app/views/roles/index.html.erb
<div id='panel-wrapper'>
  <div id='panel-header' class='text-center'>
    <span class='panel-title'>JPB Werkvergunningen</span>
  </div>
  <div id='panel-body'>
    <div class='row'>
      <div class='col-md-12'>


<p id="notice"><%= notice %></p>
<div id="main-container" class="container-fluid">
  <div class="row">

    <div id="content" class="col-xs-9">

      <p>Geregistreerde rollen</p>

      <%= grid(@roles_grid, show_filters: :always) do |g|

        g.column name: 'ID', attribute: 'id' , auto_reload: true do |role|
          role.id
        end

        g.column name: 'Naam', attribute: 'name', auto_reload: true do |role|
          role.name
        end


        g.column name: 'Beschrijving', attribute: 'description', auto_reload: true do |role|
          role.description
        end

        g.column do |role|
          #link_to('Edit', edit_enquiry_path(enq))
          link_to 'Edit', edit_enquiry_path(role), class: 'btn btn-info btn-xs'
        end
        g.column do |role|
          link_to 'Show', role, class: 'btn btn-primary btn-xs'
        end
        g.column do |role|
          link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs'
        end
      end %>
    </div>
  </div>
</div>
<br>

      </div>
    </div>
  </div>
</div>

app/views/roles/new.html.erb
<div id='panel-wrapper'>
  <div id='panel-header' class='text-center'>
    <span class='panel-title'>JPB Werkvergunningen</span>
  </div>
  <div id='panel-body'>
    <div class='row'>
      <div class='col-md-12'>


      <%= render 'form' %>

<%= link_to 'Back', roles_path %>

      </div>
    </div>
  </div>
</div>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @role.description %>
</p>

<p>
  <strong>Assosciated users:</strong>
  <%= @assosciated_users %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>